### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by NeOMakinG**
### Description:
- Adds eslint with prettier config

Feel free to correct rules I ignored, or tell me if one of then is absolutely needed

### CODE REVIEW

**Comment by A-Tokyo** [comment]
@NeOMakinG Thanks for the awesome work!

Did you get the rules from here? https://github.com/A-Tokyo/react-native-stripe-identity/blob/main/.eslintrc.json 

If not, can you do so? 🚀 

Also I noticed the extra spaces in imports where removed, can we add them back? 💪 `import { x }` instead of `import {x}`

**Comment by NeOMakinG** [comment]
I took your rules on `react-native-stripe-identity` yes!

But they're on their most recent versions.

As I took the same rules, I think they've been updated, that's why the space is gone, a default behavior may changed? But we can override the rule if you want ;)

I've no time to work on it for the moment, gonna do it this week-end probably!

**Comment by A-Tokyo** [comment]
@NeOMakinG Okay sounds great! Awesome job!

Take your time, it's not urgent.

**Comment by NeOMakinG** [comment]
Unfortunately I didn't find out the time and I'm not using the module anymore, if someone wants to continue, feel free to cherry-pick or request me access...

**Pull request closed without merging**
